version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "Installation complete."
    pre_build:
        commands:
          - pip3 install --upgrade pytest
          - python3 -m pytest
          - echo "Pre-build complete."
    build:
        commands:
          - echo "Build complete."
